### PR TITLE
Upgrade spring to version 2.0.3

### PR DESCRIPTION
**Pull request by joaopapereira**
Upgrades spring boot to version 2.0.3
Upgrades mockito to 2.19

Removes deprecated calls

Closes AgileVentures/MetPlus_tracker#684

### CODE REVIEW

**Comment by tansaku** [comment]
@joaopapereira is this ready to be merged?

**Comment by tansaku** [comment]
Ah, I see we have an error in CI:

```
/config/SpringMongoConfig.java:5: error: package org.metplus.curriculum.config does not exist
import org.metplus.curriculum.config.DatabaseConfig;
                                    ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/config/SpringMongoConfig.java:30: error: cannot find symbol
    private DatabaseConfig dbConfig;
            ^
  symbol:   class DatabaseConfig
  location: class SpringMongoConfig
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/exceptions/MandatorySettingNotPresent.java:3: error: package org.metplus.curriculum.exceptions does not exist
import org.metplus.curriculum.exceptions.CurriculumException;
                                        ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/exceptions/MandatorySettingNotPresent.java:8: error: cannot find symbol
public class MandatorySettingNotPresent extends CurriculumException{
                                                ^
  symbol: class CurriculumException
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/MetaData.java:4: error: package org.metplus.curriculum.cruncher does not exist
import org.metplus.curriculum.cruncher.CruncherMetaData;
                                      ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/MetaData.java:16: error: cannot find symbol
public class MetaData extends AbstractDocument implements CruncherMetaData {
                                                          ^
  symbol: class CruncherMetaData
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/exceptions/SettingNotFound.java:3: error: package org.metplus.curriculum.exceptions does not exist
import org.metplus.curriculum.exceptions.CurriculumException;
                                        ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/exceptions/SettingNotFound.java:8: error: cannot find symbol
public class SettingNotFound extends CurriculumException {
                                     ^
  symbol: class CurriculumException
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Resume.java:11: error: package org.metplus.curriculum.exceptions does not exist
import org.metplus.curriculum.exceptions.CurriculumException;
                                        ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/exceptions/ResumeNotFound.java:3: error: package org.metplus.curriculum.exceptions does not exist
import org.metplus.curriculum.exceptions.CurriculumException;
                                        ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/exceptions/ResumeNotFound.java:8: error: cannot find symbol
public class ResumeNotFound extends CurriculumException {
                                    ^
  symbol: class CurriculumException
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/exceptions/ResumeReadException.java:3: error: package org.metplus.curriculum.exceptions does not exist
import org.metplus.curriculum.exceptions.CurriculumException;
                                        ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/exceptions/ResumeReadException.java:8: error: cannot find symbol
public class ResumeReadException extends CurriculumException {
                                         ^
  symbol: class CurriculumException
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Resume.java:97: error: cannot find symbol
    public void setResume(InputStream fileInputStream, SpringMongoConfig dbConfig) throws CurriculumException {
                                                                                          ^
  symbol:   class CurriculumException
  location: class Resume
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/SettingsList.java:92: error: incompatible types: MandatorySettingNotPresent cannot be converted to Throwable
    public boolean isMandatoryPresent() throws MandatorySettingNotPresent {
                                               ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/SettingsList.java:95: error: incompatible types: MandatorySettingNotPresent cannot be converted to Throwable
                throw new MandatorySettingNotPresent(name, this.getClass().getSimpleName());
                ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Settings.java:58: error: incompatible types: SettingNotFound cannot be converted to Throwable
    public Setting getApplicationSetting(String name) throws SettingNotFound {
                                                             ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Settings.java:61: error: incompatible types: SettingNotFound cannot be converted to Throwable
            throw new SettingNotFound(name);
            ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Settings.java:88: error: incompatible types: CruncherSettingsNotFound cannot be converted to Throwable
    public CruncherSettings getCruncherSettings(String name) throws CruncherSettingsNotFound {
                                                                    ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Settings.java:91: error: incompatible types: CruncherSettingsNotFound cannot be converted to Throwable
            throw new CruncherSettingsNotFound(name);
            ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Settings.java:102: error: incompatible types: MandatorySettingNotPresent cannot be converted to Throwable
    public boolean validate() throws MandatorySettingNotPresent {
                                     ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Resume.java:65: error: incompatible types: ResumeNotFound cannot be converted to Throwable
    public ByteArrayOutputStream getResume(SpringMongoConfig dbConfig) throws ResumeNotFound, ResumeReadException {
                                                                              ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Resume.java:65: error: incompatible types: ResumeReadException cannot be converted to Throwable
    public ByteArrayOutputStream getResume(SpringMongoConfig dbConfig) throws ResumeNotFound, ResumeReadException {
                                                                                              ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Resume.java:84: error: incompatible types: ResumeReadException cannot be converted to Throwable
            throw new ResumeReadException(e.getMessage());
            ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Resume.java:86: error: incompatible types: ResumeNotFound cannot be converted to Throwable
            throw new ResumeNotFound(e.getMessage());
            ^
/home/travis/build/AgileVentures/MetPlus_resumeCruncher/database/src/main/java/org/metplus/curriculum/database/domain/Resume.java:116: error: cannot find symbol
            throw new CurriculumException("Error while saving the resume to the database: " + e.getMessage());
                      ^
  symbol:   class CurriculumException
  location: class Resume
26 errors
 FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':database:compileJava'.
> Compilation failed; see the compiler error output for details.
```

**Comment by joaopapereira** [comment]
Not really. I need to get some time to see what is wrong here..... Or if anyone is interested in looking into this, just let me know

**Comment by tansaku** [comment]
@joaopapereira thanks - should this be in the "in progress" rather than "needs review"?

**Comment by joaopapereira** [comment]
Closing as this PR is not working and we will replace the current cruncher

**Pull request closed without merging**
